---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opa
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://open-policy-agent.github.io/kube-mgmt/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opa-kube-mgmt
  namespace: cluster-addons
spec:
  interval: 5m
  chart:
    spec:
      chart: opa-kube-mgmt
      version: 7.3.1
      sourceRef:
        kind: HelmRepository
        name: opa
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: cert-manager
  values:
    replicaCount: 1